// Generated by @benqoder/beam (beamPlugin actionTypes). Do not edit.
// Maps your action modules into Beam's typed-action registry so action
// names, params, and ctx.json payloads are inferred at every call site.
declare module '@benqoder/beam' {
  interface BeamRegisteredActionModules {
    'app/actions/addToCart.tsx': typeof import('./actions/addToCart')
    'app/actions/animations.tsx': typeof import('./actions/animations')
    'app/actions/auth.tsx': typeof import('./actions/auth')
    'app/actions/createProduct.tsx': typeof import('./actions/createProduct')
    'app/actions/deleteProduct.tsx': typeof import('./actions/deleteProduct')
    'app/actions/demo.tsx': typeof import('./actions/demo')
    'app/actions/getProducts.tsx': typeof import('./actions/getProducts')
    'app/actions/inputs.tsx': typeof import('./actions/inputs')
    'app/actions/like.tsx': typeof import('./actions/like')
    'app/actions/loadMoreInfinite.tsx': typeof import('./actions/loadMoreInfinite')
    'app/actions/loadMoreProducts.tsx': typeof import('./actions/loadMoreProducts')
    'app/actions/react.tsx': typeof import('./actions/react')
    'app/actions/removeFromCart.tsx': typeof import('./actions/removeFromCart')
    'app/actions/streaming.tsx': typeof import('./actions/streaming')
    'app/actions/updateProduct.tsx': typeof import('./actions/updateProduct')
  }
}
export {}
