import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'

export interface BeamPluginOptions {
  /**
   * Glob pattern for action handlers (must start with '/' for virtual modules)
   * @default '/app/actions/*.tsx'
   */
  actions?: string
  /**
   * Path to auth resolver module (must export default AuthResolver function)
   * @example '/app/auth.ts'
   */
  auth?: string
  /**
   * Session configuration.
   * - `secretEnvKey`: Environment variable name containing the session secret (default: 'SESSION_SECRET')
   * - `cookieName`: Cookie name (default: 'beam_sid')
   * - `maxAge`: Cookie max age in seconds (default: 1 year)
   * - `storage`: Path to custom storage factory module (default: cookie storage)
   *
   * Set to `true` for defaults (cookie storage), or provide partial config.
   * @example
   * ```typescript
   * session: true // uses cookie storage with env.SESSION_SECRET
   * session: { secretEnvKey: 'MY_SECRET', cookieName: 'my_sid' }
   * session: { storage: '/app/session-storage.ts' } // custom KV storage
   * ```
   */
  session?: boolean | {
    secretEnvKey?: string
    cookieName?: string
    maxAge?: number
    /** Path to custom storage factory module (must export default SessionStorageFactory) */
    storage?: string
  }
  /**
   * Glob pattern for React island components (must start with '/').
   * Matched files are lazily imported (code-split) and compiled with the
   * React JSX runtime (a \/** @jsxImportSource react *\/ pragma is injected).
   * Import the registry from 'virtual:beam/islands'. Set false to disable.
   * @default '/app/islands/*.tsx'
   */
  islands?: string | false
  /**
   * Enable dynamic islands (beam-island-src): URL prefixes the client may
   * load island modules from at runtime (e.g. ['/islands/']). Setting this
   * also emits the shared react / react-dom / beam hooks files (stable names
   * under static/beam-shared/) that remote modules resolve via the import
   * map — add beamIslandImportMap() to your document head.
   * Off by default: remote sources are executable code, so every prefix here
   * is a trust decision.
   */
  islandSources?: string[]
  /**
   * Output path (root-relative, must start with '/') for the generated
   * typed-action registry d.ts. It maps your action modules into Beam's
   * types so action names, params, and ctx.json payloads are inferred in
   * useBeamAction / callBeamAction / window.beam.
   * Defaults to 'beam-actions.d.ts' next to the actions directory
   * (e.g. '/app/beam-actions.d.ts' for '/app/actions/*.tsx').
   * Set false to disable generation.
   */
  actionTypes?: string | false
}

// ============ TYPED-ACTION CODEGEN ============

function defaultActionTypesPath(actionsGlob: string): string | null {
  const starIdx = actionsGlob.indexOf('*')
  if (starIdx === -1) return null
  const dir = actionsGlob.slice(0, actionsGlob.lastIndexOf('/', starIdx)) // '/app/actions'
  const parent = dir.slice(0, dir.lastIndexOf('/')) // '/app'
  return `${parent || ''}/beam-actions.d.ts`
}

function collectActionFiles(root: string, actionsGlob: string): string[] {
  const starIdx = actionsGlob.indexOf('*')
  if (starIdx === -1) return []
  const dirRel = actionsGlob.slice(1, actionsGlob.lastIndexOf('/', starIdx))
  const dirAbs = path.join(root, dirRel)
  if (!fs.existsSync(dirAbs)) return []

  const recursive = actionsGlob.includes('**')
  const tail = actionsGlob.slice(actionsGlob.lastIndexOf('*') + 1) // e.g. '.tsx'
  const files: string[] = []

  const walk = (dir: string): void => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        if (recursive) walk(full)
      } else if (tail ? entry.name.endsWith(tail) : /\.(t|j)sx?$/.test(entry.name)) {
        files.push(full)
      }
    }
  }
  walk(dirAbs)
  return files.sort()
}

function generateActionTypes(root: string, actionsGlob: string, outPath: string): void {
  const outFile = path.join(root, outPath.startsWith('/') ? outPath.slice(1) : outPath)
  const outDir = path.dirname(outFile)
  const files = collectActionFiles(root, actionsGlob)

  const entries = files.map((file) => {
    const key = path.relative(root, file).split(path.sep).join('/')
    let rel = path.relative(outDir, file).split(path.sep).join('/').replace(/\.(t|j)sx?$/, '')
    if (!rel.startsWith('.')) rel = `./${rel}`
    return `    '${key}': typeof import('${rel}')`
  })

  const content = `// Generated by @benqoder/beam (beamPlugin actionTypes). Do not edit.
// Maps your action modules into Beam's typed-action registry so action
// names, params, and ctx.json payloads are inferred at every call site.
declare module '@benqoder/beam' {
  interface BeamRegisteredActionModules {
${entries.join('\n')}
  }
}
export {}
`

  try {
    if (fs.existsSync(outFile) && fs.readFileSync(outFile, 'utf8') === content) return
    fs.mkdirSync(outDir, { recursive: true })
    fs.writeFileSync(outFile, content)
  } catch (err) {
    console.warn('[beam] Failed to write typed-action registry:', err)
  }
}

const VIRTUAL_MODULE_ID = 'virtual:beam'
const RESOLVED_VIRTUAL_MODULE_ID = '\0' + VIRTUAL_MODULE_ID
const VIRTUAL_ISLANDS_MODULE_ID = 'virtual:beam/islands'
const RESOLVED_VIRTUAL_ISLANDS_MODULE_ID = '\0' + VIRTUAL_ISLANDS_MODULE_ID

// Shared modules for dynamic islands: emitted with stable file names so the
// import map in beamIslandImportMap() can point at them across deploys.
// Keys are virtual module ids, values are [emitted fileName, re-export code].
const SHARED_MODULE_PREFIX = 'beam-shared:'
const RESOLVED_SHARED_MODULE_PREFIX = '\0' + SHARED_MODULE_PREFIX

// react ships CommonJS, so `export * from 'react'` cannot forward named
// exports through Rollup's interop — remote modules importing
// `{ useState } from 'react'` would fail at runtime. Explicit facades
// destructure the public API into real named exports instead (destructuring
// a key missing in some react version yields undefined, not an error).
const REACT_FACADE = `import * as R from 'react'
const react = R.default && R.default.useState ? R.default : R
export const {
  Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense,
  act, cache, cloneElement, createContext, createElement, createRef, forwardRef,
  isValidElement, lazy, memo, startTransition, use, useActionState, useCallback,
  useContext, useDebugValue, useDeferredValue, useEffect, useId,
  useImperativeHandle, useInsertionEffect, useLayoutEffect, useMemo,
  useOptimistic, useReducer, useRef, useState, useSyncExternalStore,
  useTransition, version,
} = react
export default react
`

const JSX_RUNTIME_FACADE = `import * as R from 'react/jsx-runtime'
const runtime = R.default && R.default.jsx ? R.default : R
export const { Fragment, jsx, jsxs } = runtime
`

const REACT_DOM_CLIENT_FACADE = `import * as R from 'react-dom/client'
const client = R.default && R.default.createRoot ? R.default : R
export const { createRoot, hydrateRoot } = client
`

const SHARED_MODULES: Record<string, [string, string]> = {
  react: ['static/beam-shared/react.js', REACT_FACADE],
  'jsx-runtime': ['static/beam-shared/react-jsx-runtime.js', JSX_RUNTIME_FACADE],
  'react-dom-client': ['static/beam-shared/react-dom-client.js', REACT_DOM_CLIENT_FACADE],
  'beam-react': [
    'static/beam-shared/beam-react.js',
    // our own dist is real ESM — star re-export forwards named exports fine
    "export * from '@benqoder/beam/react'\n",
  ],
}

/**
 * Vite plugin that auto-generates the beam instance from handler files.
 *
 * @example
 * ```typescript
 * // vite.config.ts
 * import { beamPlugin } from '@benqoder/beam/vite'
 *
 * export default defineConfig({
 *   plugins: [
 *     beamPlugin({
 *       actions: '/app/actions/*.tsx',
 *     })
 *   ]
 * })
 * ```
 *
 * Then import the beam instance:
 * ```typescript
 * import { beam } from 'virtual:beam'
 * ```
 */
export function beamPlugin(options: BeamPluginOptions = {}): Plugin {
  const {
    actions = '/app/actions/*.tsx',
    auth,
    session,
    islands = '/app/islands/*.tsx',
    islandSources,
    actionTypes = defaultActionTypesPath(actions) ?? false,
  } = options

  // '/app/islands/*.tsx' → '/app/islands/' — used to match absolute module ids
  const islandsPrefix = islands ? islands.slice(0, islands.indexOf('*')) : null
  const dynamicIslands = Boolean(islandSources?.length)
  let emitSharedModules = false
  let projectRoot = ''

  const regenerateActionTypes = (): void => {
    if (actionTypes && projectRoot) {
      generateActionTypes(projectRoot, actions, actionTypes)
    }
  }

  return {
    name: 'beam-plugin',

    config() {
      // Statically toggles Beam's dev-only behavior: the client auto-imports
      // the dev-refresh poller and error overlay, and the server includes
      // real error details (message/stack) in action failures. All branches
      // are dead-code eliminated in production builds.
      const dev = process.env.BEAM_BUILD_DEV === '1' ? 'true' : 'false'
      return {
        define: {
          __BEAM_DEV_REFRESH__: dev,
          __BEAM_DEV__: dev,
        },
      }
    },

    configResolved(config) {
      projectRoot = config.root
      // Shared react files only make sense in the client build artifact —
      // skip the SSR/worker build and the dev server (no emitFile there).
      emitSharedModules = dynamicIslands && config.command === 'build' && !config.build.ssr
    },

    buildStart() {
      regenerateActionTypes()
      if (!emitSharedModules) return
      for (const [key, [fileName]] of Object.entries(SHARED_MODULES)) {
        this.emitFile({
          type: 'chunk',
          id: SHARED_MODULE_PREFIX + key,
          fileName,
          preserveSignature: 'strict',
        })
      }
    },

    configureServer(server) {
      // Keep the typed-action registry current as action files come and go
      const actionsDirAbs = path.join(
        projectRoot,
        actions.slice(1, actions.lastIndexOf('/', actions.indexOf('*')))
      )
      const onFileChange = (file: string): void => {
        if (file.startsWith(actionsDirAbs)) regenerateActionTypes()
      }
      server.watcher.on('add', onFileChange)
      server.watcher.on('unlink', onFileChange)
    },

    resolveId(id) {
      if (id === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_MODULE_ID
      }
      if (id === VIRTUAL_ISLANDS_MODULE_ID) {
        return RESOLVED_VIRTUAL_ISLANDS_MODULE_ID
      }
      if (id.startsWith(SHARED_MODULE_PREFIX)) {
        return '\0' + id
      }
    },

    transform(code, id) {
      // Compile island files with the React JSX runtime (the rest of the app
      // uses hono/jsx). Same-line pragma keeps line numbers intact.
      if (!islandsPrefix) return
      const file = id.split('?')[0]
      if (!file.includes(islandsPrefix) || !/\.[tj]sx$/.test(file)) return
      if (code.includes('@jsxImportSource')) return
      return { code: `/** @jsxImportSource react */ ${code}`, map: null }
    },

    load(id) {
      if (id.startsWith(RESOLVED_SHARED_MODULE_PREFIX)) {
        const key = id.slice(RESOLVED_SHARED_MODULE_PREFIX.length)
        return SHARED_MODULES[key]?.[1]
      }
      if (id === RESOLVED_VIRTUAL_ISLANDS_MODULE_ID) {
        const allowSources = dynamicIslands
          ? `import { allowIslandSources } from '@benqoder/beam/islands'
allowIslandSources(${JSON.stringify(islandSources)})
`
          : ''
        if (!islands) {
          return `${allowSources}export const islands = {}\nexport default islands\n`
        }
        // Lazy glob: each island (and React itself) is code-split and only
        // downloaded on pages that use it.
        return `${allowSources}
export const islands = import.meta.glob('${islands}')
export default islands
`
      }
      if (id === RESOLVED_VIRTUAL_MODULE_ID) {
        const authImport = auth ? `import auth from '${auth}'` : ''
        const authConfig = auth ? ', auth' : ''

        // Generate session config code
        let sessionConfig = ''
        let storageImport = ''
        if (session) {
          const sessionOpts = typeof session === 'object' ? session : {}
          const secretEnvKey = sessionOpts.secretEnvKey || 'SESSION_SECRET'
          const cookieName = sessionOpts.cookieName || 'beam_sid'
          const maxAge = sessionOpts.maxAge || 365 * 24 * 60 * 60
          const storagePath = sessionOpts.storage

          // Import custom storage factory if provided
          if (storagePath) {
            storageImport = `import storageFactory from '${storagePath}'`
          }

          // Session secret is resolved at runtime from env
          sessionConfig = `, session: {
    secret: '', // Will be resolved from env.${secretEnvKey} at runtime
    secretEnvKey: '${secretEnvKey}',
    cookieName: '${cookieName}',
    maxAge: ${maxAge}${storagePath ? ',\n    storageFactory' : ''}
  }`
        }

        // Generate plain JavaScript - TypeScript types are handled via virtual-beam.d.ts
        return `
import { createBeam, collectActions } from '@benqoder/beam'
${authImport}
${storageImport}

const actions = collectActions(import.meta.glob('${actions}', { eager: true }))

export const beam = createBeam({ actions${authConfig}${sessionConfig} })
`
      }
    },
  }
}

export default beamPlugin
